### ISSUE TITLE
有没有考虑重用机制？

### ISSUE THREAD

**Issue by ramoslin02** [iThinkerYZ/YZDisplayViewController#8]
您好，拜读了一下您的代码。您是根据水平有多少个分类标题就往里面添加多少个控制器，大的控制管理他们的. 您有没有考虑通过类似TableViewCell 的重用机制来做。 比如在水平添加三个控制器，通过重用他们达到效果呢？ 或者其他方式来提搞性能呢？因为水平有6七个还行，如果水平有30个的话，是不是要加载30个控制器呢？这样感觉性能挺不好的。谢谢。

**Comment by xxycode** [comment]
你这个想法就有问题，为什么要重用 ？你能保证所有的控制器都是tabviewController？要是没过控制器类型都不一样呢
