### ISSUE TITLE
底部的下标线的长度能定制嘛？想均分长度

### ISSUE THREAD

**Issue by liujieyuu** [iThinkerYZ/YZDisplayViewController#9]
底部的下标线的长度能定制嘛？想均分长度

**Comment by donggelaile** [comment]
作者近期好像比较忙，没有啥回复。。。  我在作者的基础上做了改进，修复了几个小bug，新增了均匀滑条及滑块模式，并不影响原来已有的效果。如果还需要的话留接收方式吧。

**Comment by liujieyuu** [comment]
@donggelaile 大哥，你不给我提取码怎么行？

**Comment by donggelaile** [comment]
@liujieyuu 我记得后来改成了公开链接的。。。竟然没换过来。  现在可以了，上边那个可以下载了。  失误，失误。。。

**Comment by liujieyuu** [comment]
@donggelaile 谢谢
